config/routes.rb
Rails.application.routes.draw do

  get 'forces/index'
  get 'forces/test01'
  get 'forces/test02'
  get 'forces/test03'
  get 'forces/test04'
  get 'forces/test05'

  get 'japan_maps/index'
  get 'japan_maps/list'

  get 'sample_graph/index'
  get 'sample_graph/list'

  root 'toppages#index'

  get 'posts/index', to: 'posts#index'
  get 'posts/list', to: 'posts#list'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/forces_controller.rb
class ForcesController < ApplicationController
  def index
  end

  def test01
  end

  def test02
  end

  def test03
  end

  def test04
  end

  def test05
  end
  
end

app/controllers/japan_maps_controller.rb
class JapanMapsController < ApplicationController
  def index
  end

  def list

  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def list
    data = [

      {date: "2018-01-1",close:"50"},
      {date:"2018-01-02",close:"53"},
      {date:"2018-01-03",close:"55"},
      {date:"2018-01-04",close:"60"},
      {date:"2018-01-05",close:"69"},
      {date:"2018-01-06",close:"76"},
      {date:"2018-01-07",close:"78"},
      {date:"2018-01-08",close:"83"},
      {date:"2018-01-09",close:"90"}
    ]
    render :json => data

  end
end

app/controllers/sample_graph_controller.rb
class SampleGraphController < ApplicationController
  def index
  end

  def list
    data = []
    31.times do |i|
      data.push({date:"2017-01-#{i}",close: rand(20..30)})
    end
    render :json => data
  end

end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/helpers/forces_helper.rb
module ForcesHelper
end

app/helpers/japan_maps_helper.rb
module JapanMapsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sample_graph_helper.rb
module SampleGraphHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/views/forces/index.html.erb
<script src="http://d3js.org/d3.v3.min.js" charset="utf-8"></script>
<script type="text/javascript">
  var width = 800;
  var height = 800;
  // nodeの定義。ここを増やすと楽しい
  var nodes = [
    { id: 0, label: "A" },
    { id: 1, label: "B" },
    { id: 2, label: "C" },
    { id: 3, label: "D" },
    { id: 4, label: "E" },
    { id: 5, label: "F" },
    { id: 6, label: "G" },
    { id: 7, label: "H" },
    { id: 8, label: "I" },
    { id: 9, label: "J" },
    { id: 10, label: "K" },
    { id: 11, label: "L" },
    { id: 12, label: "M" },
    { id: 13, label: "N" }

  ];

  // nodeどうしの紐付け設定。ここをどう作るかが難しい。
  var links = [
    { source: 0, target: 1 },
    { source: 0, target: 2 },
    { source: 0, target: 3 },
    { source: 0, target: 4 },
    { source: 0, target: 5 },
    { source: 0, target: 6 },
    { source: 0, target: 7 },
    { source: 3, target: 3 },
    { source: 4, target: 2 },
    { source: 4, target: 1 },
    { source: 5, target: 6 },
    { source: 6, target: 7 },
    { source: 6, target: 1 },
    { source: 7, target: 1 },
    { source: 7, target: 2 },
    { source: 8, target: 8 },
    { source: 9, target: 9 },
    { source: 9, target: 10 },
    { source: 9, target: 11 },
    { source: 9, target: 12 },
    { source: 10, target: 12 },
    { source: 11, target: 8 },
    { source: 11, target: 13 },
    { source: 12, target: 11 },
    { source: 12, target: 5 },
    { source: 13, target: 9 },


  ];
  // forceLayout自体の設定はここ。ここをいじると楽しい。
  var force = d3.layout.force()
      .nodes(nodes)
      .links(links)
      .size([width, height])
      .distance(200) // node同士の距離
      .friction(0.5) // 摩擦力(加速度)的なものらしい。
      .charge(10) // 寄っていこうとする力。推進力(反発力)というらしい。
      .gravity(0) // 画面の中央に引っ張る力。引力。
      .start();

  // svg領域の作成
  var svg = d3.select("body")
      .append("svg")
      .attr({width:width, height:height});

  // link線の描画(svgのline描画機能を利用)
  var link = svg.selectAll("line")
      .data(links)
      .enter()
      .append("line")
      .style({stroke: "#ccc",
      "stroke-width": 5
  });

  // nodesの描画(今回はsvgの円描画機能を利用)
  var node = svg.selectAll("circle")
      .data(nodes)
      .enter()
      .append("circle")
      .attr({ // せっかくなので半径をランダムに
          r: function() {return Math.random() * (70 - 10) + 10;}
        })
      .style({
          fill: "orange"
      })
      .call(force.drag);

  // nodeのラベル周りの設定
  var label = svg.selectAll('text')
      .data(nodes)
      .enter()
      .append('text')
      .attr({
          "text-anchor":"middle",
          "fill":"white",
          "font-size": "9px"
      })
      .text(function(data) { return data.label; });

  // tickイベント(力学計算が起こるたびに呼ばれるらしいので、座標追従などはここで)
  force.on("tick", function() {
      link.attr({
          x1: function(data) { return data.source.x;},
          y1: function(data) { return data.source.y;},
          x2: function(data) { return data.target.x;},
          y2: function(data) { return data.target.y;}
      });
      node.attr({
          cx: function(data) { return data.x;},
          cy: function(data) { return data.y;}
      });
      // labelも追随するように
      label.attr({
          x: function(data) { return data.x;},
          y: function(data) { return data.y;}
      });
  });
</script>

app/views/forces/test01.html.erb
<h1>forces#test01</h1>
<%= javascript_include_tag src='https://d3js.org/d3.v3.min.js' %>
<script type="text/javascript">
  var width = 800;
  var height = 800;

  var nodes = [
    { id: 0, label: "A" },
    { id: 1, label: "B" },
    { id: 2, label: "C" },
    { id: 3, label: "D" },
    { id: 4, label: "E" }
  ];

  var links = [
    { source: 0, target: 4 },
    { source: 0, target: 3 },
    { source: 0, target: 2 },
    { source: 0, target: 1 },

  ];

  var force = d3.layout.force()
      .nodes(nodes)
      .links(links)
      .size([width, height])
      .distance(200)
      .friction(0.5)
      .charge(10)
      .gravity(0)
      .start();

  var svg = d3.select("body")
        .append("svg")
        .attr({width:width, height: height});

  var link = svg.selectAll("line")
        .data(links)
        .enter()
        .append("line")
        .style({ stroke: "#ccc",
          "stroke-width" : 5
        })

  var node = svg.selectAll("circle")
              .data(nodes)
              .enter()
              .append("circle")
              .attr({r: 20,
                     opacity: 0.5})
              .style({"fill": "red"})
              .call(force.drag);

  var label = svg.selectAll('text')
                .data(nodes)
                .enter()
                .append('text')
                .attr({"text-anchor":"middle",
                       "fill":"white"})
                .style({"font-size":11})
                .text(function(d) { return d.label; });

  force.on("tick", function() {
  link.attr({x1: function(d) { return d.source.x; },
             y1: function(d) { return d.source.y; },
             x2: function(d) { return d.target.x; },
             y2: function(d) { return d.target.y; }});
  node.attr({cx: function(d) { return d.x; },
             cy: function(d) { return d.y; }});
  label.attr({x: function(d) { return d.x; },
              y: function(d) { return d.y; }});
  });
</script>

app/views/forces/test02.html.erb
<h1>forces#test02</h1>
<%= javascript_include_tag src='https://d3js.org/d3.v3.min.js' %>
<script>
    var width = 640;
    var height = 480;

    var svg = d3.select('body').append('svg').attr({
        width: width,
        height: height
    });

    var data = {
        nodes: [
            { name: 'aki' },
            { name: 'mii' },
            { name: 'akiton' }
        ],
        links: [
            { source: 0, target: 2 },
            { source: 1, target: 2 }
        ]
    };

    var force = d3.layout.force()
        .nodes(data.nodes)
        .links(data.links)
        .size([width, height])
        .gravity(0.1)
        .charge([-100])
        .friction(0.95)
        .linkDistance([100])
        .linkStrength(1);

    // レイアウト計算開始
    force.start();
    for (var i = 0; i < 10000; i++) {
        force.tick();
    }
    force.stop();

    // lineを生成
    var line = svg.selectAll('line')
        .data(data.links)
        .enter()
        .append('line')
        .attr({
            'stroke': 'black',
            'x1': function(d, i) { return d.source.x; },
            'y1': function(d, i) { return d.source.y; },
            'x2': function(d, i) { return d.target.x; },
            'y2': function(d, i) { return d.target.y; }
        })
        .style({
        });

    var circle = svg.selectAll('circle')
        .data(data.nodes)
        .enter()
        .append('circle')
        .attr({
            'r': 8,
            'fill': 'black',
            'cx': function(d, i) { return d.x; },
            'cy': function(d, i) { return d.y; }
        })
        .style({
        });
        // .call(force.drag);

    var moveTarget = null;
    circle
        .on('mousedown', function(d, i) {
            console.log(d.name + '(' + d.x + ',' + d.y + ')');
            moveTarget = d;
        })
        .on('mouseup', function(d, i) {
            moveTarget = null;
        });

    svg.on('mousemove', function(e) {
        if (moveTarget != null) {
            var mousePos = d3.mouse(this);
            console.log('moveTarget = ' + moveTarget.name + ' (' + mousePos[0] + ',' + mousePos[1] + ')');
            moveTarget.x = mousePos[0];
            moveTarget.y = mousePos[1];

            d3.selectAll('line')
                .attr({
                    'x1': function(d) { return d.source.x; },
                    'y1': function(d) { return d.source.y; },
                    'x2': function(d) { return d.target.x; },
                    'y2': function(d) { return d.target.y; }
                });
            d3.selectAll('circle')
                .attr({
                    'cx': function(d) { return d.x; },
                    'cy': function(d) { return d.y; }
                });
        }
    });

    svg.on('mousedown', function() {
        if (moveTarget != null) return;
        var newCircle = svg.append('circle');
        var mousePos = d3.mouse(this);
        var newData = {
            name: 'super',
            age: 10,
            x: mousePos[0],
            y: mousePos[1]
        };
        data.nodes.push(newData);
        console.log('add circle: ' + newData.x + ',' + newData.y);
        newCircle
            .datum(newData)
            .attr({
                'cx': function(d, i) { console.log(d);return d.x; },
                'cy': function(d, i) { return d.y; },
                'r': 10,
                'fill': 'red'
            })
            .on('mousedown', function(d) {
                moveTarget = d;
            })
            .on('mouseup', function(d) {
                moveTarget = null;
            });
        svg.append('text')
            .datum(newData)
            .text(function(d, i) { return d.name; })
            .attr({
                'font-size': '12',
                'stroke': 'white',
                'x': function(d, i) { return d.x; },
                'y': function(d, i) { return d.y; }
            });
    });

    function randomMove() {
        for (var i = 0; i < data.nodes.length; i++) {
            var d = data.nodes[i];
            d.x += Math.random() * 2 <= 1 ? Math.random()*10 : -Math.random()*10;
            d.y += Math.random() * 2 <= 1 ? Math.random()*10 : -Math.random()*10;

            d3.selectAll('line')
                .attr({
                    'x1': function(d) { return d.source.x; },
                    'y1': function(d) { return d.source.y; },
                    'x2': function(d) { return d.target.x; },
                    'y2': function(d) { return d.target.y; }
                });
            d3.selectAll('circle')
                .attr({
                    'cx': function(d) { return d.x; },
                    'cy': function(d) { return d.y; }
                });
            d3.selectAll('text')
                .attr({
                    'x': function(d) { return d.x; },
                    'y': function(d) { return d.y; }
                });
        }
    }
</script>
<input type="button" value="randomMove" onClick="randomMove()"/>

app/views/forces/test03.html.erb
<h1>foces#test03</h1>
<style>

.links line {
  stroke: #999;
  stroke-opacity: 0.6;
}

.nodes circle {
  stroke: #fff;
  stroke-width: 1.5px;
}

</style>
<svg width="960" height="600"></svg>
<%= javascript_include_tag src='https://d3js.org/d3.v4.min.js' %>
<script>

var svg = d3.select("svg"),
    width = +svg.attr("width"),
    height = +svg.attr("height");

var color = d3.scaleOrdinal(d3.schemeCategory20);

var simulation = d3.forceSimulation()
    .force("link", d3.forceLink().id(function(d) { return d.id; }))
    .force("charge", d3.forceManyBody())
    .force("center", d3.forceCenter(width / 2, height / 2));

d3.json("<%= asset_path('miserables.json') %>", function(error, graph) {
  if (error) throw error;

  var link = svg.append("g")
      .attr("class", "links")
    .selectAll("line")
    .data(graph.links)
    .enter().append("line")
      .attr("stroke-width", function(d) { return Math.sqrt(d.value); });

  var node = svg.append("g")
      .attr("class", "nodes")
    .selectAll("circle")
    .data(graph.nodes)
    .enter().append("circle")
      .attr("r", 5)
      .attr("fill", function(d) { return color(d.group); })
      .call(d3.drag()
          .on("start", dragstarted)
          .on("drag", dragged)
          .on("end", dragended));

  node.append("title")
      .text(function(d) { return d.id; });

  simulation
      .nodes(graph.nodes)
      .on("tick", ticked);

  simulation.force("link")
      .links(graph.links);

  function ticked() {
    link
        .attr("x1", function(d) { return d.source.x; })
        .attr("y1", function(d) { return d.source.y; })
        .attr("x2", function(d) { return d.target.x; })
        .attr("y2", function(d) { return d.target.y; });

    node
        .attr("cx", function(d) { return d.x; })
        .attr("cy", function(d) { return d.y; });
  }
});

function dragstarted(d) {
  if (!d3.event.active) simulation.alphaTarget(0.3).restart();
  d.fx = d.x;
  d.fy = d.y;
}

function dragged(d) {
  d.fx = d3.event.x;
  d.fy = d3.event.y;
}

function dragended(d) {
  if (!d3.event.active) simulation.alphaTarget(0);
  d.fx = null;
  d.fy = null;
}

</script>

app/views/forces/test04.html.erb
<style>
  .node {
    cursor: pointer;
    stroke: #3182bd;
    stroke-width: 1.5px;
  }

  .link {
    fill: none;
    stroke: #9ecae1;
    stroke-width: 1.5px;
}
</style>
<body>
  <script src="//d3js.org/d3.v3.min.js"></script>
  <script>

    var width = 960,
        height = 500,
        root;

    var force = d3.layout.force()
        .size([width, height])
        .on("tick", tick);

    var svg = d3.select("body").append("svg")
        .attr("width", width)
        .attr("height", height);

    var link = svg.selectAll(".link"),
        node = svg.selectAll(".node");

    d3.json("<%= asset_path('test04.json') %>", function(error, json) {
      if (error) throw error;

      root = json;
      update();
    });

    function update() {
      var nodes = flatten(root),
          links = d3.layout.tree().links(nodes);

      // Restart the force layout.
      force
          .nodes(nodes)
          .links(links)
          .start();

      // Update the links…
      link = link.data(links, function(d) { return d.target.id; });

      // Exit any old links.
      link.exit().remove();

      // Enter any new links.
      link.enter().insert("line", ".node")
          .attr("class", "link")
          .attr("x1", function(d) { return d.source.x; })
          .attr("y1", function(d) { return d.source.y; })
          .attr("x2", function(d) { return d.target.x; })
          .attr("y2", function(d) { return d.target.y; });

      // Update the nodes…
      node = node.data(nodes, function(d) { return d.id; }).style("fill", color);

      // Exit any old nodes.
      node.exit().remove();

      // Enter any new nodes.
      node.enter().append("circle")
          .attr("class", "node")
          .attr("cx", function(d) { return d.x; })
          .attr("cy", function(d) { return d.y; })
          .attr("r", function(d) { return Math.sqrt(d.size) / 10 || 4.5; })
          .style("fill", color)
          .on("click", click)
          .call(force.drag);
    }

    function tick() {
      link.attr("x1", function(d) { return d.source.x; })
          .attr("y1", function(d) { return d.source.y; })
          .attr("x2", function(d) { return d.target.x; })
          .attr("y2", function(d) { return d.target.y; });

      node.attr("cx", function(d) { return d.x; })
          .attr("cy", function(d) { return d.y; });
    }

    // Color leaf nodes orange, and packages white or blue.
    function color(d) {
      return d._children ? "#3182bd" : d.children ? "#c6dbef" : "#0000EE";
    }

    // Toggle children on click.
    function click(d) {
      if (!d3.event.defaultPrevented) {
        if (d.children) {
          d._children = d.children;
          d.children = null;
        } else {
          d.children = d._children;
          d._children = null;
        }
        update();
      }
    }

    // Returns a list of all nodes under the root.
    function flatten(root) {
      var nodes = [], i = 0;

      function recurse(node) {
        if (node.children) node.children.forEach(recurse);
        if (!node.id) node.id = ++i;
        nodes.push(node);
      }

      recurse(root);
      return nodes;
    }

  </script>
</body>

app/views/forces/test05.html.erb
<h1>forces#test05</h1>
<style>

body {
  background-color: white;
}

.link {
  stroke: #777;
  stroke-opacity: 0.3;
  stroke-width: 1.5px;
}

.node circle {
  fill: #ccc;
  stroke: #000;
  stroke-width: 1.5px;
}

.node text {
  display: none;
  font: 10px sans-serif;
}

.node:hover circle {
  fill: #000;
}

.node:hover text {
  display: inline;
}

.cell {
  fill: none;
  pointer-events: all;
}

</style>
<body>
  <script src="//d3js.org/d3.v3.min.js"></script>
  <script>

  var width = 960,
      height = 500

  var svg = d3.select("body").append("svg")
      .attr("width", width)
      .attr("height", height);

  var force = d3.layout.force()
      .gravity(0.1)
      .charge(-120)
      .linkDistance(30)
      .size([width, height]);

  var voronoi = d3.geom.voronoi()
      .x(function(d) { return d.x; })
      .y(function(d) { return d.y; })
      .clipExtent([[0, 0], [width, height]]);

  d3.json("<%= asset_path('test05.json') %>", function(error, json) {
    if (error) throw error;

    force
        .nodes(json.nodes)
        .links(json.links)
        .start();

    var link = svg.selectAll(".link")
        .data(json.links)
      .enter().append("line")
        .attr("class", "link");

    var node = svg.selectAll(".node")
        .data(json.nodes)
      .enter().append("g")
        .attr("class", "node")
        .call(force.drag);

    var circle = node.append("circle")
        .attr("r", 4.5);

    var label = node.append("text")
        .attr("dy", ".35em")
        .text(function(d) { return d.name; });

    var cell = node.append("path")
        .attr("class", "cell");

    force.on("tick", function() {
      cell
          .data(voronoi(json.nodes))
          .attr("d", function(d) { return d.length ? "M" + d.join("L") : null; });

      link
          .attr("x1", function(d) { return d.source.x; })
          .attr("y1", function(d) { return d.source.y; })
          .attr("x2", function(d) { return d.target.x; })
          .attr("y2", function(d) { return d.target.y; });

      circle
          .attr("cx", function(d) { return d.x; })
          .attr("cy", function(d) { return d.y; });

      label
          .attr("x", function(d) { return d.x + 8; })
          .attr("y", function(d) { return d.y; });
    });
  });

  </script>
</body>

app/views/forces/test_one.html.erb
<h1>forces#test_one</h1>
<%= javascript_include_tag src='https://d3js.org/d3.v3.min.js' %>
<script type="text/javascript">
  var width = 800;
  var height = 800;

  var nodes = [
    { id: 0, label: "A" },
    { id: 1, label: "B" },
    { id: 2, label: "C" },
    { id: 3, label: "D" },
    { id: 4, label: "E" }
  ];

  var links = [
    { source: 0, target: 4 },
    { source: 0, target: 3 },
    { source: 0, target: 2 },
    { source: 0, target: 1 },

  ];

  var force = d3.layout.force()
      .nodes(nodes)
      .links(links)
      .size([width, height])
      .distance(200)
      .friction(0.5)
      .charge(10)
      .gravity(0)
      .start();

  var svg = d3.select("body")
        .append("svg")
        .attr({width:width, height: height});

  var link = svg.selectAll("line")
        .data(links)
        .enter()
        .append("line")
        .style({ stroke: "#ccc",
          "stroke-width" : 5
        })

  var node = svg.selectAll("circle")
              .data(nodes)
              .enter()
              .append("circle")
              .attr({r: 20,
                     opacity: 0.5})
              .style({"fill": "red"})
              .call(force.drag);

  var label = svg.selectAll('text')
                .data(nodes)
                .enter()
                .append('text')
                .attr({"text-anchor":"middle",
                       "fill":"white"})
                .style({"font-size":11})
                .text(function(d) { return d.label; });

  force.on("tick", function() {
  link.attr({x1: function(d) { return d.source.x; },
             y1: function(d) { return d.source.y; },
             x2: function(d) { return d.target.x; },
             y2: function(d) { return d.target.y; }});
  node.attr({cx: function(d) { return d.x; },
             cy: function(d) { return d.y; }});
  label.attr({x: function(d) { return d.x; },
              y: function(d) { return d.y; }});
  });
</script>

app/views/japan_maps/index.html.erb
<%= javascript_include_tag src='https://d3js.org/d3.v3.min.js' %>
<%= javascript_include_tag src='http://d3js.org/topojson.v1.min.js' %>

<script>
  var width = 2000,
  height = 1800;

  var svg = d3.select("body").append("svg")
  .attr("width", width)
  .attr("height", height);

  var color = d3.scale.category20();

  // 地理座標から画面表示への投影法の設定。
  var mercator = d3.geo.mercator()
      .center([ 136.0, 35.6 ])
      .translate([width/2, height/2])
      .scale(800);

  // geojsonからpath要素を作るための設定。
  var geopath = d3.geo.path()
  .projection(mercator);

  // topojsonファイルの読み込み
  d3.json("<%= asset_path('japan_topojson.json') %>", function(error, jp) {
      console.log(jp);

      // topojsonからgeojsonへの変換。
      var geoJp = topojson.feature(jp, jp.objects.ne_10m_admin_1_states_provinces);
      console.log(geoJp);

      svg.selectAll("path")
          .data(geoJp.features) // geojsonのすべての県の座標データを読み込む。
        .enter().append("path")
          .attr("class", function(d) { return d.id; })
          .attr("d", geopath) // geojsonからpath要素に変換する。
          .attr("fill", function(d){ return color(d.geometry.coordinates); }); // idがないので、各県の座標リストに基づいて色を変える。
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>D3Test</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%= javascript_include_tag src='https://d3js.org/d3.v4.min.js' %>
<script>

// set the dimensions and margins of the graph
// グラフの大きさやマージンを設定
var margin = {top: 20, right: 20, bottom: 30, left: 50},
    width = 960 - margin.left - margin.right,
    height = 500 - margin.top - margin.bottom;

// parse the date / time
// 取り込むデータを解析するパーサーを設定
var parseTime = d3.timeParse("%Y-%m-%d");

// set the ranges
// scaleとrangeを設定
var x = d3.scaleTime().range([0, width]);
var y = d3.scaleLinear().range([height, 0]);

// define the line
// 折れ線グラフ作成用のジェネレータ（関数）を定義
var valueline = d3.line()
    .x(function(d) { return x(d.date); })
    .y(function(d) { return y(d.close); });

// append the svg obgect to the body of the page
// appends a 'group' element to 'svg'
// moves the 'group' element to the top left margin
// svgの領域を設定
var svg = d3.select("body").append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform",
          "translate(" + margin.left + "," + margin.top + ")");

// Get the data
// データの取り込み（データをフォーマット/「domain」を設定/svgにグラフ情報を与える）

d3.json('list', function(error, data) {
 if (error) throw error;

  // format the data
  //取り込まれたデータをフォーマットする処理
  data.forEach(function(d) {
      d.date = parseTime(d.date);
      d.close = +d.close;
  });

  // Scale the range of the data
  // domainの定義（d3.extendはd3.jsの関数（最小と最大を返す））
  x.domain(d3.extent(data, function(d) { return d.date; }));
  y.domain([0, d3.max(data, function(d) { return d.close; })]);

  // Add the valueline path.
  // 作成したsvg領域にグラフ部分であるpath領域をX,Y軸部分であるg領域を作成
  svg.append("path")
      .data([data])
      .attr("class", "line")
      .attr("d", valueline);

  // Add the X Axis
  svg.append("g")
      .attr("transform", "translate(0," + height + ")")
      .call(d3.axisBottom(x));

  // Add the Y Axis
  svg.append("g")
      .call(d3.axisLeft(y));

});

</script>

app/views/sample_graph/index.html.erb
<%= javascript_include_tag src='https://d3js.org/d3.v4.min.js' %>

<script>

// set the dimensions and margins of the graph
var margin = {top: 20, right: 20, bottom: 30, left: 50},
    width = 960 - margin.left - margin.right,
    height = 500 - margin.top - margin.bottom;

// parse the date / time
var parseTime = d3.timeParse("%Y-%m-%d");

// set the ranges
var x = d3.scaleTime().range([0, width]);
var y = d3.scaleLinear().range([height, 0]);

// define the line
var valueline = d3.line()
    .x(function(d) { return x(d.date); })
    .y(function(d) { return y(d.close); });

// append the svg obgect to the body of the page
// appends a 'group' element to 'svg'
// moves the 'group' element to the top left margin
var svg = d3.select("body").append("svg")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform",
          "translate(" + margin.left + "," + margin.top + ")");

// Get the data
d3.json('list', function(error, data) {
 if (error) throw error;

  // format the data
  data.forEach(function(d) {
      d.date = parseTime(d.date);
      d.close = +d.close;
  });

  // Scale the range of the data
  x.domain(d3.extent(data, function(d) { return d.date; }));
  y.domain([0, d3.max(data, function(d) { return d.close; })]);

  // Add the valueline path.
  svg.append("path")
      .data([data])
      .attr("class", "line")
      .attr("d", valueline);

  // Add the X Axis
  svg.append("g")
      .attr("transform", "translate(0," + height + ")")
      .call(d3.axisBottom(x));

  // Add the Y Axis
  svg.append("g")
      .call(d3.axisLeft(y));

});

</script>

app/views/toppages/index.html.erb
<h1>Toppages#index</h1>
<p><%= link_to "折れ線グラフtest01", sample_graph_index_path %></p>
<p><%= link_to "折れ線グラフtest02", posts_index_path %></p>
<p><%= link_to "日本地図test03", japan_maps_index_path %></p>
<p><%= link_to "force_basic", forces_index_path %></p>
<p><%= link_to "forces_test01", forces_test01_path %></p>
<p><%= link_to "forces_test02", forces_test02_path %></p>
<p><%= link_to "forces_test03", forces_test03_path %></p>
<p><%= link_to "forces_test04", forces_test04_path %></p>
<p><%= link_to "forces_test05", forces_test05_path %></p>